services:
  calibre-web-automated:
    image: ghcr.io/crocodilestick/calibre-web-automated:dev
    container_name: calibre-web-automated
    restart: always

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - ADMIN_USERNAME=alexhouse
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme123}
      - HARDCOVER_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJIYXJkY292ZXIiLCJ2ZXJzaW9uIjoiOCIsImp0aSI6ImZjYTRkMmUyLWRiOTEtNGEwMS04MDNhLWUzMGQ1ZDZlZTI4OSIsImFwcGxpY2F0aW9uSWQiOjIsInN1YiI6IjUwMzEwIiwiYXVkIjoiMSIsImlkIjoiNTAzMTAiLCJsb2dnZWRJbiI6dHJ1ZSwiaWF0IjoxNzYxNTM2NDgyLCJleHAiOjE3OTMwNzI0ODIsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1yb2xlIjoidXNlciIsIlgtaGFzdXJhLXVzZXItaWQiOiI1MDMxMCJ9LCJ1c2VyIjp7ImlkIjo1MDMxMH19.LLEDcRer6dkJdLQ_h5sxtsFGnXq5t3bHmcnLKxoSp3U

    volumes:
      - cwa_config:/config
      - /library/ingest:/cwa-book-ingest
      - /library:/calibre-library
      - /library/plugins:/config/.config/calibre/plugins

    ports:
      - "8083:8083"

    deploy:
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 400M

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: always
    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=0.0.0.0:8384

    volumes:
      - syncthing_config:/var/syncthing
      - /library:/library

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

volumes:
  cwa_config:
    driver: local
  syncthing_config:
    driver: local
