services:
  calibre-web-automated:
    image: ghcr.io/crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    restart: unless-stopped

    environment:
      # User/Group IDs - change if needed to match your user
      - PUID=1000
      - PGID=1000
      # Timezone - update to match your location
      # See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Chicago
      # Optional: Hardcover API token for metadata enrichment
      # Get your token at: https://docs.hardcover.app/api/getting-started/
       - HARDCOVER_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJIYXJkY292ZXIiLCJ2ZXJzaW9uIjoiOCIsImp0aSI6ImZjYTRkMmUyLWRiOTEtNGEwMS04MDNhLWUzMGQ1ZDZlZTI4OSIsImFwcGxpY2F0aW9uSWQiOjIsInN1YiI6IjUwMzEwIiwiYXVkIjoiMSIsImlkIjoiNTAzMTAiLCJsb2dnZWRJbiI6dHJ1ZSwiaWF0IjoxNzYxNTM2NDgyLCJleHAiOjE3OTMwNzI0ODIsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1yb2xlIjoidXNlciIsIlgtaGFzdXJhLXVzZXItaWQiOiI1MDMxMCJ9LCJ1c2VyIjp7ImlkIjo1MDMxMH19.LLEDcRer6dkJdLQ_h5sxtsFGnXq5t3bHmcnLKxoSp3U
      # Optional: Enable for network shares (NFS/SMB) to prevent DB locking issues
      # - NETWORK_SHARE_MODE=false

    volumes:
      # CWA configuration directory (named volume for persistence)
      - cwa_config:/config
      # Ingest directory - files placed here are automatically added to library
      # WARNING: Files are REMOVED after processing
      - /library/ingest:/cwa-book-ingest
      # Calibre library directory - will be auto-created if doesn't exist
      - /library:/calibre-library

    ports:
      # Web UI and KOSync server (change left number to change access port)
      - "8083:8083"

    deploy:
      resources:
        limits:
          memory: 1500M  # Critical for RPi 4 2GB - prevents OOM
        reservations:
          memory: 400M

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped

    # Use host network for proper local discovery
    # This is recommended by Syncthing for optimal functionality
    network_mode: host

    environment:
      # User/Group IDs - should match CWA settings
      - PUID=1000
      - PGID=1000
      # GUI address - leave unset for localhost-only (secure default)
      # Set to empty string to bind to all interfaces
      - STGUIADDRESS=

    volumes:
      # Syncthing configuration and database
      - syncthing_config:/var/syncthing
      # Library access for sync (configured as ONE-WAY in future epics)
      - /library:/library

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

# Named volumes for data persistence across container restarts
volumes:
  cwa_config:
    driver: local
  syncthing_config:
    driver: local

# Notes:
# - Default credentials for CWA: admin/admin123 (change on first login!)
# - CWA Web UI: http://raspberrypi.local:8083
# - Syncthing Web UI: http://raspberrypi.local:8384
# - /library directory must exist on host before deployment
# - Syncthing uses host networking for proper device discovery
